branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-21.1.1
    - android-21
    - doc-MNC
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21

script:
  - ./gradlew clean testDebug --info

after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
