branches:
  only:
    - master

language: android
sudo: false
jdk:
  - oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    # - doc-MNC
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=12

before_script:
  - mksdcard -l mySdCard 1024M mySdCardFile.img
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -sdcard mySdCardFile.img -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  #- android list target
  - ./gradlew connectedDebugAndroidTest coveralls --info

#after_success:
  #- ./gradlew coveralls --info
 # - ./scripts/publish_snapshot.sh

#cache:
# directories:
#    - $HOME/.gradle
#    - $HOME/.m2/repository
